import { type NextPage } from "next";
import Head from "next/head";

import { api, RouterOutputs } from "~/utils/api";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) return null;

  return <div className="flex">
    <img src={user.profileImageUrl} className="h-12 rounded-full" alt={"avatar"} />
    <input placeholder={"Type some emojis!"} className="bg-transparent p-2 text-slate-400" />
  </div>;
};

type PostWithUser = RouterOutputs["example"]["getAll"][number]

const PostView = ({ post, author }: PostWithUser) => {
  return <div key={post.id} className="border-b border-slate-400 p-8">
    <h1>{post.content}</h1>
  </div>;
};

const Home: NextPage = () => {
  const user = useUser();
  const { data, isLoading } = api.example.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>;

  if (!data) return <div>Something went wrong</div>;

  console.log(data);
  console.log(user);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="w-full md:max-w-2xl border-x border-slate-400">
          <div className="border-b border-slate-400 p-4">
            <div className="flex justify-center">
              {!user.isSignedIn && <SignInButton />}
              {user.isSignedIn && (<div className="flex content-between w-full justify-between">
                <CreatePostWizard />
                <SignOutButton />
              </div>)}
            </div>
          </div>
          {data.map(( fullPost ) => (
            <PostView  {...fullPost} key={fullPost.post.id} />
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
